### ISSUE TITLE
JHU data may be wrong

### ISSUE THREAD

**Issue by qianxliu** [winsphinx/covid-cn#1]
据我建模和对比分析来看，JHU的数据并不是很准确

**Comment by qianxliu** [comment]
@winsphinx Do you find that? compare it with China official post and see what happened

**Comment by winsphinx** [comment]
@Neteraxe 可能是统计口径不一样，也可能是宣传口径不一样。具体情况谁也不知道，谁也不敢想。

**Comment by qianxliu** [comment]
@winsphinx 
我用的就是这个包
https://github.com/Kamaropoulos/COVID19Py

中国累计
![image](https://user-images.githubusercontent.com/53852392/161195362-0b954668-da63-4ea0-b872-e91805e6bb49.png)
他这个包的实现是不是有什么问题
https://voice.baidu.com/act/newpneumonia/newpneumonia/?from=osari_aladin_banner

**Comment by qianxliu** [comment]
就是全国数据差异很大

**Comment by winsphinx** [comment]
粗略看了下，HK的差异非常大，以3.30为例，我查到几个来源累计确诊都是28w，JHU的统计有115w。

**Comment by qianxliu** [comment]
你能查明白问题在哪里吗
用COVID19Py包中jhu接口，确认只有1037，但是官方是2000+
建模时发现了这个问题，感觉数据很奇怪

**Comment by qianxliu** [comment]
COVID19Py显示的jhu确诊数据明显不合理，建模时也发现了

**Comment by qianxliu** [comment]
破案了，COVID19Py这个包肯定实现有问题
https://github.com/Kamaropoulos/COVID19Py
JHU数据基本是正确的
![image](https://user-images.githubusercontent.com/53852392/161213060-23d9c49c-295b-49bf-97a4-5dc44ca3d136.png)

**Comment by qianxliu** [comment]
有空你可以给他们提交一下PR, this bug is very terrible
